# Generated by Django 5.0.7 on 2024-07-30 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesores',
            fields=[
                ('documento', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesde_api.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Aspirantes',
            fields=[
                ('celular', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('documento', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('cel_opcional', models.CharField(blank=True, max_length=15)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesde_api.ciudad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesde_api.estados')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesde_api.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Gestiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, max_length=300)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesde_api.asesores')),
                ('cel_aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesde_api.aspirantes')),
                ('tipo_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesde_api.tipo_gestion')),
            ],
        ),
    ]
