# Generated by Django 5.1 on 2024-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="nit",
            field=models.CharField(max_length=50),
        ),
    ]
