# Generated by Django 5.0.7 on 2024-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipificacion",
            name="contacto",
            field=models.BooleanField(default=False),
        ),
    ]
