# Generated by Django 5.0.7 on 2024-08-28 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="asesor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.asesores",
            ),
        ),
    ]
