# Generated by Django 5.1 on 2024-08-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="fecha",
            field=models.DateField(db_index=True),
        ),
    ]
