# Generated by Django 5.0.7 on 2024-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirantes",
            name="correo",
            field=models.EmailField(max_length=50),
        ),
    ]
