# Generated by Django 5.1 on 2024-08-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0002_alter_empresa_nit"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestiones",
            name="empresa",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
