# Generated by Django 5.0.7 on 2024-08-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0002_alter_tipificacion_contacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestiones",
            name="asesor",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.asesores",
            ),
        ),
    ]
