# Generated by Django 5.1 on 2024-08-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0002_alter_gestiones_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="fecha",
            field=models.DateField(),
        ),
    ]
