# Generated by Django 5.0.7 on 2024-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0002_alter_aspirantes_correo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirantes",
            name="correo",
            field=models.CharField(max_length=50),
        ),
    ]
