# Generated by Django 5.1 on 2024-08-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0002_rename_documento_asesores_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="fecha",
            field=models.DateTimeField(),
        ),
    ]
