# Generated by Django 5.1 on 2024-08-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0002_rename_documento_asesores_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipificacion",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Interesado", "Interesado"),
                    ("En seguimiento", "En seguimiento"),
                    ("No contactado", "No contactado"),
                    ("Descartado", "Descartado"),
                    ("Opcional", "Opcional"),
                ],
                default="Opcional",
                max_length=50,
            ),
        ),
    ]
