# Generated by Django 5.1 on 2024-09-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0003_alter_aspirantes_correo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estados",
            name="nombre",
            field=models.CharField(max_length=20),
        ),
    ]
