# Generated by Django 5.0.7 on 2024-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0003_gestiones_asesor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asesores",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="asesores",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="asesores",
            name="nombre",
        ),
        migrations.AddField(
            model_name="asesores",
            name="id",
            field=models.CharField(
                default=1, max_length=15, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asesores",
            name="nombre_completo",
            field=models.CharField(default="Jefferson Montoya", max_length=70),
            preserve_default=False,
        ),
    ]
