# Generated by Django 5.0.7 on 2024-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cesde_api",
            "0004_remove_asesores_apellido_remove_asesores_documento_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirantes",
            name="cel_opcional",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="descripcion",
        ),
        migrations.AlterField(
            model_name="programa",
            name="nombre",
            field=models.CharField(max_length=70),
        ),
    ]
