# Generated by Django 5.1 on 2024-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0005_alter_estados_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirantes",
            name="fecha_ingreso",
            field=models.CharField(default="Octubre", max_length=30),
        ),
        migrations.AddField(
            model_name="aspirantes",
            name="fecha_modificacion",
            field=models.DateField(blank=True, default=None),
        ),
    ]
