# Generated by Django 5.1 on 2024-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0005_alter_tipificacion_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipificacion",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Interesado", "Interesado"),
                    ("En seguimiento", "En seguimiento"),
                    ("No contactado", "No contactado"),
                    ("Descartado", "Descartado"),
                    ("Opcional", "Opcional"),
                ],
                default="Opcional",
                max_length=50,
            ),
        ),
    ]
