# Generated by Django 5.0.7 on 2024-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0005_remove_aspirantes_cel_opcional_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirantes",
            name="apellidos",
        ),
        migrations.AlterField(
            model_name="aspirantes",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
