# Generated by Django 5.0.7 on 2024-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0006_remove_aspirantes_apellidos_alter_aspirantes_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="fecha",
            field=models.DateField(),
        ),
    ]
