# Generated by Django 5.0.7 on 2024-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0006_remove_aspirantes_apellidos_alter_aspirantes_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipificacion",
            name="valor_tipificacion",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
