# Generated by Django 5.1 on 2024-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0006_aspirantes_fecha_ingreso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirantes",
            name="correo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="aspirantes",
            name="fecha_modificacion",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nit",
            field=models.CharField(max_length=70),
        ),
    ]
