# Generated by Django 5.0.7 on 2024-08-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0007_tipificacion_valor_tipificacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirantes",
            name="estado",
        ),
    ]
