# Generated by Django 5.1 on 2024-10-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0007_alter_aspirantes_correo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirantes",
            name="detalle",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
