# Generated by Django 5.0.7 on 2024-08-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0007_tipificacion_valor_tipificacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirantes",
            name="estado",
        ),
        migrations.AddField(
            model_name="gestiones",
            name="estado",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.estados",
            ),
            preserve_default=False,
        ),
    ]
