# Generated by Django 5.0.7 on 2024-08-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0008_remove_aspirantes_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestiones",
            name="estado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.estados",
            ),
        ),
    ]
