# Generated by Django 5.0.7 on 2024-08-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0009_gestiones_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cesde_api.estados"
            ),
        ),
    ]
