# Generated by Django 5.0.7 on 2024-08-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0010_alter_gestiones_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestiones",
            name="estado",
        ),
    ]
