# Generated by Django 5.0.7 on 2024-08-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0010_alter_gestiones_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipificacion",
            name="gestion_final",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Interesado", "Interesado"),
                    ("Descartado", "Descartado"),
                    ("No Contactado", "No Contactado"),
                    ("En Seguimiento", "En Seguimiento"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gestiones",
            name="estado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.estados",
            ),
        ),
    ]
