# Generated by Django 5.0.7 on 2024-08-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0011_remove_gestiones_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirantes",
            name="estado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.estados",
            ),
            preserve_default=False,
        ),
    ]
