# Generated by Django 5.0.7 on 2024-08-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0011_tipificacion_gestion_final_alter_gestiones_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestiones",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="tipificacion",
            name="gestion_final",
        ),
        migrations.AddField(
            model_name="aspirantes",
            name="estado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.estados",
            ),
        ),
    ]
