# Generated by Django 5.0.7 on 2024-08-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0012_aspirantes_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirantes",
            name="empresa",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="Empresa",
        ),
    ]
