# Generated by Django 5.0.7 on 2024-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0012_remove_gestiones_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="fecha",
            field=models.DateField(),
        ),
    ]
