# Generated by Django 5.0.7 on 2024-08-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0012_remove_tipificacion_gestion_final"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestiones",
            name="estado",
        ),
        migrations.AddField(
            model_name="aspirantes",
            name="estado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cesde_api.estados",
            ),
        ),
    ]
