# Generated by Django 5.0.7 on 2024-08-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0013_alter_aspirantes_empresa_delete_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirantes",
            name="empresa",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
