# Generated by Django 5.0.7 on 2024-08-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cesde_api", "0015_empresa_alter_aspirantes_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestiones",
            name="fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
