FROM python:3.12.4

# Configura el directorio de trabajo
WORKDIR /app

# Copia el archivo de requisitos
COPY requirements.txt .

# Instala las dependencias en un entorno virtual
RUN python -m venv venv \
    && . venv/bin/activate \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

# Copia el resto del código del proyecto
COPY . .

# Expone el puerto que tu aplicación usará
EXPOSE 8000

# Define el intérprete de Python a usar en el entorno virtual
ENV PATH="/app/venv/bin:$PATH"

# Ejecuta las migraciones y luego inicia el servidor dentro del entorno virtual
CMD ["bash", "-c", "source /app/venv/bin/activate && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
