# Usa una imagen base de Python
FROM python:3.12.4

# Configura el directorio de trabajo
WORKDIR /app

# Copia el archivo de requisitos
COPY requirements.txt .

# Crea un entorno virtual y activa
RUN python -m venv venv \
    && . venv/bin/activate \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

# Copia el resto del código del proyecto
COPY . .

# Expone el puerto si tu aplicación lo usa
EXPOSE 8000

# Define el intérprete de Python a usar
ENV PATH="/app/venv/bin:$PATH"

# Ejecuta las migraciones y luego inicia el servidor
CMD ["bash", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]